name: app_porto
description: "Maqueta solo pagina inicio"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  flutter_widget_from_html: ^0.17.0
  youtube_player_iframe: ^5.2.2
  flutter_svg: ^2.2.0
  share_plus: ^11.1.0
  http: ^1.2.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.0.0
  http_parser: ^4.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/img/
    - assets/img/webp/
    - assets/img/eventos/
    - assets/img/eventosWebp/
    - assets/img/eventos/panama2025/
    - assets/img/eventos/barranquilla2024/
    - assets/img/eventos/medellin2023/
    - assets/img/categorias/
    - assets/img/sponsors/
    - assets/img/conocenos/
    - assets/img/conocenos/instalaciones/
    - assets/img/thumbs/
    - assets/img/profes/
    - assets/img/tienda/
   
