name: app_porto
description: "Maqueta solo pagina inicio"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  flutter_widget_from_html: ^0.17.0
  youtube_player_iframe: ^5.2.2
  flutter_svg: ^2.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/categorias/
    - assets/icons/
   
